# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99d09b3b8d532874c23d60bd70a7de28e9afe3db92b8aa4a510ee585928a7ec192ccf9c72726be640cf69783f02a72a806ae5661d882e1d61c730cc7e5914490

test:
  secret_key_base: 943cc959b54fd0efab0277c35d47ed85def078e0cfe2ad120eae91bc16426365e41bac45c3868b34078b15f1677736bda3109f6dd6efe105e3e505be25ad8776

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
